#!ruby
# Go here to start from app's root directory.
Dir.chdir File.expand_path(File.dirname(__FILE__) + "/..")
# If using Bundler, you might need to uncomment next two lines
#require "bundler"
#Bundler.setup
require "resque/forker"

# Load the application.
Resque.setup do |forker|
  require File.expand_path('../../config/environment', __FILE__)
  ActiveRecord::Base.connection.disconnect!
  forker.options.interval = 1
  if Rails.env.production?
    forker.logger = Rails.logger
    forker.workload = ["*"] * 4        # 4 workers on all queues
    forker.user "www-data", "www-data" # don't run as root
  else
    forker.options.verbose = true
  end
end
# Stuff to do after forking a worker.
Resque.before_first_fork do
  ActiveRecord::Base.establish_connection
end
Resque.fork!
