#!/usr/bin/env ruby
require "resque/forker"

# Load the application.
Resque.setup do |forker|
  require File.dirname(__FILE__) + "/../config/environment"
  ActiveRecord::Base.connection.disconnect!
  if Rails.env.production?
    forker.logger = Rails.logger
    forker.workload = ["*"] * 4        # 4 workers on all queues
    forker.user "www-data", "www-data" # don't run as root
    forker.options.interval = 1
  else
    forker.options.verbose = true
  end
end
# Stuff to do after forking a worker.
Resque.before_first_fork do
  ActiveRecord::Base.establish_connection
end
Resque.fork!
